### ISSUE TITLE
Solver libraries fail to load on linux

### ISSUE THREAD

**Issue by MarkoSchuetz** [AlloyTools/org.alloytools.alloy#103]
Alloy fails to load dynamic libraries of the included solvers from the jar file.

I installed alloy from AUR on 64 bit Linux. The jar file does contain e.g.

    99085 Sun Feb 22 19:21:37 AST 2015 amd64-linux/libglucose.so

However, when I launch alloy, I get messages:

    Failed to load: libglucose.so

How do I get alloy to find these libraries?

**Comment by avanegas-carecloud** [comment]
I have the same problem on Windows 10.  The messages are:

```
Failed to load: minisat.dll
Failed to load: minisatprover.dll
Failed to load: lingeling.dll
Failed to load: glucose.dll
Failed to load: cryptominisat.dll
```

**Comment by jiayiyang1997** [comment]
I ran it on Windows 10 and met the same problem. Finally I found it was because the .dll given is 32bits while my JVM is 64bits. Thus the library wasn't loaded successfully. Now I'm trying to install a 32bits JVM and run it again.

**Comment by andrewsoutar** [comment]
As a workaround, I've found that if you extract the libraries from the jar (they'll be in amd64-linux or x86-linux) and point your LD_LIBRARY_PATH at the extracted copies, Alloy will pick them up just fine. e.g.
```bash
unzip org.alloytools.alloy.dist.jar -d alloy-unzip 'amd64-linux/*'
LD_LIBRARY_PATH="$(pwd)/alloy-unzip/amd64-linux" java -jar org.alloytools.alloy.dist.jar
```
Not sure what the equivalent would be on Windows but I would imagine it might work there too.

**Comment by pkriens** [comment]
Please check against 6,0 and reopen when it still fails.

**Comment by BranAndSceolan** [comment]
Hello, I am using the Alloy analyser visual studio code extension which uses 
```
Build Date: 2021-11-19T05:45:51.188Z Git Commit: d597bc141c2b7347097f500844baf9d37bd5a0d9
```
as well as the alloy analyser jar which uses
```
6.1.0 built 2021-11-03T15:25:43.736Z
```

In both Instances, I am experiencing the problem described here. I am using Ubuntu Jammy Jellyfish as my operating system.

**Comment by BranAndSceolan** [comment]
While I don't get the "failed to load" messages, most of the SAT solvers (including MiniSat with Unsat Core) do not appear. The trick of unzipping the file and changing the path works as a workaround.
