### ISSUE TITLE
License

### ISSUE THREAD

**Issue by marcellussiegburg** [AlloyTools/org.alloytools.alloy#104]
I would like to redistribute AlloyTools within an own library. This is required for a project of mine. However, I am not sure, how I should redistribute your license / reference this project.
Is this project in fact published under MIT License or is it Apache as the license file suggests?

I think, this should be clarified by either removing the comment in the first line of the license file or changing the license file.

**Comment by pkriens** [comment]
The project was published under the Apache license. Originally it was MIT but when we moved to GH it was decided to move it to Apache. This was verbally approved by the people involved in the project at the time.
