### ISSUE TITLE
Tooltip shows text that's difficult to read

### ISSUE THREAD

**Issue by nikolakasev** [AlloyTools/org.alloytools.alloy#106]
![image](https://user-images.githubusercontent.com/9705009/69061567-af50f500-0a19-11ea-9cd4-6a5fb960c043.png)

+ Leaving the mouse on the predicate should keep the tooltip visible until the mouse moves (currently it disappears after five seconds) - should this be a separate issue?

**Comment by pkriens** [comment]
Is this still true in the current 6.0 release? Please reopen if so
