### ISSUE TITLE
Remove `exh` and `part` from errors, syntax

### ISSUE THREAD

**Issue by hwayne** [AlloyTools/org.alloytools.alloy#110]
From http://alloytools.org/quickguide/a4.html

> We don’t allow “part” and “exh” in declarations any more.

Both can show up in syntax errors

![image](https://user-images.githubusercontent.com/2660212/78817003-202c8580-7998-11ea-92bd-7b946f07df69.png)

**Comment by pkriens** [comment]
These tokens are still defined in the parser in cup.lex, the error is generated inside the parser.

I can easily remove them, say the word ...

Kind regards,

	Peter Kriens

**Comment by hwayne** [comment]
If we don't need to be backwards compatible with Alloy 3, I see no reason to keep them.

**Comment by pkriens** [comment]
@dnjackson if you ok,  can remove these keywords
