### ISSUE TITLE
Editor: cursor vanishes

### ISSUE THREAD

**Issue by kbraith1-ford** [AlloyTools/org.alloytools.alloy#116]
I have Alloy 5.1.0 running in JRE 1.8.0 on MacOS 10.14.6 I dowloaded the prebuilt dmg, but I have seen this same behaviour after building a copy of the source repo.

I find that the cursor in the editor pane occasionally vanishes. Sometimes, if I navigate using the cursor keys the line and column figures in the status bar at the bottom update as I'd expect, but the cursor is not visible and other keystrokes are not registerd. That is, no characters are inserted into the buffer. Sometimes the status bar does not get updated. If I point into the pane with the mouse, the line and column numbers do change, but the cursor is still invisible.

I saw the earlier report regarding strange editor behaviour and indeed my problem seemed to occur less frequently after changing the font to Menlo, but it has not disasspeared.

Additional: the failure seems to be related to the Alloy window losing and regaining focus.

**Comment by pkriens** [comment]
@kbraith1-ford could you reopen this bug when you still have this problem in 6.x?
