### ISSUE TITLE
Zoom In/Zoom Out + Navigation tooltips

### ISSUE THREAD

**Issue by ronchon65** [AlloyTools/org.alloytools.alloy#120]
Electrum Analyzer 2.0.0.202006030639

Concerning the graph display tool:
 - When trying to zoom in or zoom out a graph (popup menu), right clicking any point in the left or right window only affects the right window. Is it really the expected behavior ?

- The tooltips associated to the right and left navigation arrows are inverted (a bit confusing).

**Comment by nmacedo** [comment]
Both issues are fixed as of 6.1.
