### ISSUE TITLE
Inconsistent results between Alloy 5 and Alloy 5.1 (related to int-usage assumptions)

### ISSUE THREAD

**Issue by gregistecco** [AlloyTools/org.alloytools.alloy#123]
There is a problem with some commands wrongly reporting an unsatisfiable result. The results are inconsistent with previous versions of Alloy 5. For instance, the model attached should find pred test1 to be satisfiable, but the command:

run test1 expect 1

gives an unsatisfiable outcome. It reports “0 vars. 0 primary vars. 0 clauses”.

I think the problem has to do with the use of integers. A potential fix is changing line:

 _boolean shouldUseInts = true; // TODO CompUtil.areIntsUsed(sigs, cmd);_(https://github.com/AlloyTools/org.alloytools.alloy/blob/ee124f9d782e04493a4171b7e06842e2a4c5070e/org.alloytools.alloy.core/src/main/java/edu/mit/csail/sdg/translator/ScopeComputer.java#L351)

by
**boolean shouldUseInts = CompUtil.areIntsUsed(sigs,cmd);**

(Notice that CompUtil should also be imported)
**import edu.mit.csail.sdg.parser.CompUtil;**

---
module unknown
sig Node {
adj: (set Node)
}
pred noLoops[] {
(adj = (iden - (Node->Node)))
}

pred test1 {
	some disj Node1, Node2 : Node | {		
       Node = (Node1 + Node2)
	   no adj
       noLoops[]
	}
}
run test1 expect 1

**Comment by pkriens** [comment]
Could you try this out in the latest 6.0 release and re-open this big if it still fails?
