### ISSUE TITLE
Updating Java from 1.8?

### ISSUE THREAD

**Issue by zsfre** [AlloyTools/org.alloytools.alloy#124]
According to the README, Alloy builds with versions of Java up to 1.8. Is there any interest in upgrading the version to 11 or beyond? Apart, I believe, from performance improvements, the main changes are some syntax and library improvements (switch as an expression, yay!), and modules. I believe that gradle is now updated.

**Comment by pkriens** [comment]
No, there is no reason to upgrade since the later JVMs add very little value and just make it harder to use Alloy in older envs.
