### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by SanatBhandari** [AlloyTools/org.alloytools.alloy#125]
Hi, 

I was going over the documentation and saw that the README says `java version` to check the latest version of Java to operate Alloy. However, it should be `java -version` which is the correct command. 

It is a minor issue but something that would be beneficial for newbies. 

Thanks!

**Comment by pkriens** [comment]
Just fix it on Github. This will send a PR? Is easier than an issue.

**Comment by pkriens** [comment]
fixed
