### ISSUE TITLE
Feature Request: Unsigned Integers

### ISSUE THREAD

**Issue by hwayne** [AlloyTools/org.alloytools.alloy#146]
When you specify the integer bitwidth in alloy, it always gives you signed integers, ie writing `run {} for 3 Int` will give you `{-4, ... 3}`. Many models only need the positive integers, so we'd get more state space coverage by allowing unsigned integers.

Example spec:

```als
sig Resource {
  cost: Int
}

run {sum[univ.cost] <= 5} for 3 Int
```

This will give a lot of specs where Resources have negative costs, and there's no way for a Resource to cost 4.

**Comment by grayswandyr** [comment]
After discussion, it seems like a to complex task regarding the available developer manpower, while there exists a natural module.
