### ISSUE TITLE
Add simple CLI to Alloy

### ISSUE THREAD

**Issue by grayswandyr** [AlloyTools/org.alloytools.alloy#155]
It would be nice to be able to choose various options from the commandline and to print an instance. @nmacedo  had developed a simple CLI for electrum, might be cool to reframe it for Alloy.

**Comment by pkriens** [comment]
I did some work for someone that was blind. Needs a lot of polishing but works surprisingly well: https://github.com/AlloyTools/org.alloytools.alloy/pull/151

```alloy
$ java -jar alloy.jar shell test.als
> /help

Available sub-commands: 

  cache                       -  
  compile                     -  
  exec                        -  
  find                        -  
  next                        -  
  prev                        -  
  print                       -  
  run                         -  
  sigs                        -  


> /sigs
this/Foo
> # Foo
   5 vars. 4 primary vars. 2 clauses.
   SAT!
1
> 1.plus[2]
{3}
> /next
[main] INFO kodkod.engine.config.Reporter - solving p cnf 5 3
> # Foo
1
> /next
[main] INFO kodkod.engine.config.Reporter - solving p cnf 5 4
> #Foo
2
> /print -t
---INSTANCE---
loop=0
end=0
integers={-8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7}
------State 0-------
univ={Foo$0, Foo$1, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7}
Int={-8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7}
seq/Int={0, 1, 2, 3}
String={}
none={}
this/Foo={Foo$0, Foo$1}

> /print
┌────────┐
│this/Foo│
├────────┤
│Foo¹    │
├────────┤
│Foo²    │
└────────┘

> /prev
> /print -t
---INSTANCE---
loop=0
end=0
integers={-8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7}
------State 0-------
univ={Foo$0, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7}
Int={-8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7}
seq/Int={0, 1, 2, 3}
String={}
none={}
this/Foo={Foo$0}

> /compile test2.als
> #Foo
Syntax error at line 1 column 2:
Error
  0. [CompModule.hint] The name "Foo" cannot be found. #Foo
> #Bar
   0 vars. 0 primary vars. 0 clauses.
   SAT!
0
> /run { # Bar > 4 } for 5
sig Bar {}


run __foo { # Bar > 4 } for 5
   39 vars. 5 primary vars. 85 clauses.
   SAT!
> # Bar
5

**Comment by grayswandyr** [comment]
As a matter of fact, I thought of this issue for the same reason :-)
The thing I was thinking about was more like a batch interface (as it can also be used by external tools or to run tests from the commandline). But I think your idea of a TUI (text user interface) is also great. I'd say we need both.

**Comment by pkriens** [comment]
I just showed the shell but I actually started with a pure command line, just implemented the shell and then started to realize that it is probably easiest if we make a shell but allow commands to be piped through this shell. I quickly found that most interesting things require a lot of command options

**Comment by grayswandyr** [comment]
@pkriens could you launch a discussion on Discourse about a spec for a CLI? I suppose it could start with your work in progress.
