### ISSUE TITLE
Feature request: then as synonym for ;

### ISSUE THREAD

**Issue by esb-dev** [AlloyTools/org.alloytools.alloy#157]
Alloy often has two notations for operators i.e. and/&&. Some people prefer the more verbose notation.
I propose to introduce the operator "then" as a synonym for "," the trace sequence operator.

I think in the code one has to add just one line in Alloy.lex

`"then"                { return alloy_sym(yytext(), CompSym.TRCSEQ      );}`

after line 234.

But one has to change documentation  and It's a question of the conceptual integrity of the language too. But imho it would fit.

--Burkhardt

**Comment by pkriens** [comment]
Language changes must be approved by the board. I suggest you start a discussion on https://alloytools.discourse.group/ and gather feedback. After some gestation time and receiving positive feedback, ping me and I will submit it to the board.
