### ISSUE TITLE
New Application

### ISSUE THREAD

**Issue by poz1** [AlloyTools/org.alloytools.alloy#16]
Hello!
I am working on a new application to work with alloy code, I'm using a combination of JavaFX & Javascript that allows me to use [Monaco](https://microsoft.github.io/monaco-editor/) so to have intellisense, snippets and many other goodies. 

Is there someone else who is working on something similar? 

Attached a screenshot of the "alpha" :) 

<img width="1680" alt="screen shot 2017-11-03 at 21 10 42" src="https://user-images.githubusercontent.com/10652822/32394039-186333b6-c0dc-11e7-826f-f7a4ef9bd956.png">

**Comment by pkriens** [comment]
There are ideas to move to the web. However, JavaFX is one of the last technologies I would use today? The future seems more web oriented and Java is unfortunately not a nice technology, most browsers go out of their way to disable it.

I think it would be cool to have a Javascript GUI that uses a REST API for storage and analysing. I could set up a server and provide such an API. It would be fantastic if there was an Angular/Backbone or Alloy(!) front end.

Kind regards,

	Peter Kriens

**Comment by poz1** [comment]
Well actually my idea was to use an "Electron" approach: Java for the logic and JS + HTML & CSS for the GUI. It is meant to be executed locally (at least for now :) )

JavaFX is used just as a "container" with a WebView

**Comment by pkriens** [comment]
I guess we can close this?
