### ISSUE TITLE
Can't run Alloy on Kubuntu 20.04

### ISSUE THREAD

**Issue by IgorArnaut** [AlloyTools/org.alloytools.alloy#161]
Greetings,
I have Kubuntu 20.04 installed and OpenJDK 11 installed. If I try to execute Alloy with OpenJDK 11 Runtime, Duke icon flashes on task manager and nothing happens, but if I try to execute it through command line, I get "Unable to start graphical environment" error.
How do I solve this? I need a solution ASAP.

EDIT: I also have OpenJDK 17 installed on my system.

**Comment by createyourpersonalaccount** [comment]
Did you fix your problem? I had fixed mine by installing more java related packages. The fedora java package was stripped without the graphical stuff and I had to runn `dnf install java-latest-openjdk`.

**Comment by IgorArnaut** [comment]
I just installed Java 8.
