### ISSUE TITLE
Feature Request: watches in visualizer/evaluator

### ISSUE THREAD

**Issue by rix0rrr** [AlloyTools/org.alloytools.alloy#167]
When my model gets large, it becomes very hard to see what's going on. 

At some point the visualizer becomes too cluttered, and the table view doesn't go deep enough to get the information that I want.

What would be extremely helpful is if I could use the evaluator to create "watches" similar to debuggers in other programming languages: let me input some expression, and automatically evaluate them at every time step (or when new results are being visualized).

That way I can craft expressions for the information I'm interested in, and read those as I'm stepping through the trace.

**Comment by grayswandyr** [comment]
Hi, this is already possible, though not through the Evaluator. The way to do this is to create so-called "derived relations", that is `fun`ctions without explicit parameter whose values are %Mcumputed at runtime%. See e.g. [this page for an example, more precisely in the Event Reification section](https://alloytools.discourse.group/t/modelling-a-state-machine-in-electrum-towards-alloy-6/88) (the example is in the context of behavior modeling but notice that this approach is totally independant from this specific use case).
