### ISSUE TITLE
Meta capabilities does not work

### ISSUE THREAD

**Issue by cdelg** [AlloyTools/org.alloytools.alloy#174]
Since Alloy 6 meta capabilities does not seem to work. If you try the following program:

```alloy
sig A {
	 attr: lone B
}

sig B{}

run {
	all f:field$| some f.value
}
```
with Alloy 6 we get:

> Fatal Error: the solver ran out of stack space!
> Try simplifying your model or reducing the scope,
> or increase stack under the Options menu.

Works as expected with Alloy 5.1

**Comment by grayswandyr** [comment]
Tracked in #194
