### ISSUE TITLE
Issue visualizing skolem funs with past operators

### ISSUE THREAD

**Issue by nmacedo** [AlloyTools/org.alloytools.alloy#178]
When considering past operators, the value of expressions may change depending on which loop unrolling it is being evaluated. Instances in the visualizer only have the value of the prefix (and the looping state), and skolem functions are statically calculated and registered in the prefix. If a function has past operators, and its value changes depending on the loop unrolling, it will always show in the visualizer its value in the first unrolling. 

Minimal example:
```
some var sig A {}
run {always A = A'}

fun x : A {
	{ a:A | not before a in A }
}
```
Function `x` is equal to `A` in the first unrolling, but empty in the remaining, but it always appear as `A` in the visualizer. 

PS: the evaluator works fine since the values are calculated dynamically.

**Comment by alcinocunha** [comment]
I think the behaviour with skolem functions should be the same as if they were declared as signatures or fields. In this case we should have the same behaviour as if the model was
```alloy
some var sig A {}
run {always A = A'}

var sig x in A {}
fact { always x = { a:A | not before a in A } }
```
which works fine.

To implement this correctly we need to compute the maximum depth of past operator nesting in all the skolems (in this case it is 1) and unroll the trace in the generated instance that many times, so that we make enough states distinct in the prefix for the past formulas to make sense. I'm not sure how easy it is to implement this?

**Comment by nmacedo** [comment]
I'm having a lot of trouble fixing this. I see two options:

- We assume the skolem functions are part of the trace, and unroll the trace accordingly when processing the Pardinus trace into XML for the visualizer. This option is easy to implement, but may perhaps give surprising solutions. For instance, in the example above the Pardinus trace has a single looping state, but after unrolling it will show as follows. A consequence is that solutions may no longer be provided with increasing length.  Maybe I can try to use the original state identifiers in the visualizer, so that it at least just shows transitions between state 0?

<img width="396" alt="Screenshot 2024-03-27 at 14 28 28" src="https://github.com/AlloyTools/org.alloytools.alloy/assets/3604584/b4beb67c-2ae8-4d12-b79e-426e3ed13629">

- We assume that skolem functions are not part of the trace, do not unroll the trace for the visualizer, and dynamically calculate the value of those functions when navigating the trace in the visualizer. While this seems simple in principle, the instance visualization and the evaluator are completely disconnected, and neither has access to the definition of the skolem functions, so I can't find an elegant way to implement this.

**Comment by nmacedo** [comment]
Ok, new plan: I unroll the trace at the XML level, but register information about the original trace. So in the example above, even though the value of the skolem function changes, it would still show like this:
<img width="395" alt="Screenshot 2024-03-27 at 15 25 32" src="https://github.com/AlloyTools/org.alloytools.alloy/assets/3604584/8aff8a90-53a1-4c00-a985-7334e1ac16b1">

So the user still sees the instance as minimal, in the sense that the trace shows only a state 0. The only tradeoff is that the XML get a bit messy: the header says it's a trace with a single instance, but it actually contains two distinct states.

**Comment by alcinocunha** [comment]
The proposed solution looks great!
