### ISSUE TITLE
Outdated/Incomplete instructions for IntelliJ

### ISSUE THREAD

**Issue by saiema** [AlloyTools/org.alloytools.alloy#187]
Current instructions are:

```
1. Choose "Import Project"
2. Select the org.alloytools.alloy directory.
3. Choose "Import project from external model: Bnd/Bndtools" and click "Next"
4. For "Select Bnd/Bndtools project to import", all projects should be checked by default, click "Next"
5. For project SDK, Choose "1.8", Click Finish
```

But for current version of IntelliJ Ultimate (2022.1.4), I find the following issues:

1. "Import project" does not exist, the closest option is `Import project from existing Sources`.
2. This step can be reproduced.
3. This step can be reproduced.
4. This step can be reproduced.
5. This step can be reproduced.

After following previous steps, running `src/main/java/edu/mit/csail/sdg/alloy4whole/SimpleGUI.java` yields the following output in the console:

```
Failed to load: libminisat.so
Failed to load: libminisatprover.so
Failed to load: liblingeling.so
Failed to load: libglucose.so
Failed to load: libcryptominisat.so
```

This can be solved but requires copying files and modifying modules' configuration. But it looks that it should not be solved this way.

Maybe the instructions requires an update.

PS: The [Osmorc plugin](https://plugins.jetbrains.com/plugin/1816-osmorc) states that it is already included in IntelliJ Ultimate so there is no need to download it.

**Comment by saiema** [comment]
Adding the folder `org/alloytools/kodkod/nativesat/jni` as a `Resource Folder` solves the issue, maybe that is the solution?

Maybe the instructions should state

```
1. Choose `Import project from existing Sources` by using `Ctrl + Shift + a`.
2. Select the root folder (default folder name is `org.alloytools.alloy`).
3. Choose "Import project from external model: Bnd/Bndtools" and click "Next"
4. For "Select Bnd/Bndtools project to import", all projects should be checked by default, click "Next"
5. For project SDK, Choose "1.8", Click Finish
6. Select folder `org/alloytools/kodkod/nativesat/jni` as `Resource Folder` by selecting module `org.alloytools.kodkod.nativesat`, selecting folder `jni` -> `right click` -> `Mark Directory As` -> `Resource Root`.
```

**Comment by pkriens** [comment]
Updated README.md, hope it works :-)
