### ISSUE TITLE
Running Alloy in IntelliJ: java.lang.NoClassDefFoundError: org/sat4j/specs

### ISSUE THREAD

**Issue by RuomeiYan** [AlloyTools/org.alloytools.alloy#188]
Dear Alloy team,

I am trying to get Alloy repo running in IntelliJ to use features such as the debugger, however after cloning the repo and following all the instructions for setting up in IntelliJ, I encountered the error below:
`Unknown exception occurred: java.lang.NoClassDefFoundError: org/sat4j/specs/ContradictionException`

This happens whenever it tries to execute a command. I understand this should be a problem with setting up IDE, but I've been stuck on this for several days now. The Gradle build and running jar to get the GUI have been working fine for me, just cannot get it working in IntelliJ. Do I need to pre-install sat4j?

Any insights would be highly appreciated!
Thank you!

Stack trace:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/34190239/197375835-d0ef25af-0461-4b0d-bc8c-c17c7240a25a.png">

Sincerely,
Ruomei Yan

**Comment by pkriens** [comment]
I am not sure what you're trying to do here? What instructions are you following here?
