### ISSUE TITLE
PLingleling and Lingeling with hybrid and parallel decomposed strategies

### ISSUE THREAD

**Issue by soaresCecilia** [AlloyTools/org.alloytools.alloy#189]
I'm using Alloy Analyzer 6.1.0, java version 15 and a macOS Monterey version 12.6, with 3,5 GHz Intel Core i7 dual core and 16GB of memory.

With Alloy sample model **_leader_events_** when executing the command _**Run example**_ or any check command with solvers PLingeling and Lingeling in parallel or hybrid decomposed strategies no instance is found. Besides, there are no vars or primary vars.

However, executing the same commands with the same strategies, but any different solver the outcome is different, i.e., the run command will find an instance and the check commands will handle some vars and primary vars.

**Comment by grayswandyr** [comment]
Thanks for the report. Can you provide the source file please?

**Comment by soaresCecilia** [comment]
You can find the source file here:

https://github.com/AlloyTools/org.alloytools.alloy/blob/master/org.alloytools.alloy.extra/extra/models/examples/temporal/leader_events.als

**Comment by nmacedo** [comment]
Fixed for 6.2 (Pardinus 1.3.1).
