### ISSUE TITLE
Add split panes for text, table and tree view

### ISSUE THREAD

**Issue by grayswandyr** [AlloyTools/org.alloytools.alloy#193]
Currently we have a split view for the graphical depiction of consecutive states in the Visualizer, but not for the text, table and tree views. Diff-like colors would even be nice in these views (at least the text one).

**Comment by nmacedo** [comment]
Very basic implementation for text and table views for 6.2:
<img width="1544" alt="Screenshot 2023-04-14 at 19 10 59" src="https://user-images.githubusercontent.com/3604584/232124216-d234c5ff-4ba2-4ae0-91cf-f7e3c5752f0e.png">
<img width="1262" alt="Screenshot 2023-04-14 at 19 10 49" src="https://user-images.githubusercontent.com/3604584/232124240-3fa4645f-cca4-4558-b81b-0b2533f777e2.png">

**Comment by grayswandyr** [comment]
@nmacedo thank you so much, you rock! 
Can you point me to the commit implementing this?

**Comment by pkriens** [comment]
This great! I can adapt the drawings of the box to use constant vertical space & ordering so the stay on the same place.

**Comment by nmacedo** [comment]
> @nmacedo thank you so much, you rock! Can you point me to the commit implementing this?

It's [here](https://github.com/nmacedo/org.alloytools.alloy/blob/4fad15daba3bb7173c860ce001283571de2765f7/org.alloytools.alloy.application/src/main/java/edu/mit/csail/sdg/alloy4viz/VizGUI.java#L1190). It's nothing fancy, it just tests if the line/table was present in the previous state.

**Comment by nmacedo** [comment]
> 



> * When a piece of highlighted text is selected, its color doesn't change. After a quick web search, it seems like there's a way to make selection of highlighted text visible...?

I'll look into it.

> * The diff could be finer-grained by only highlighting added and removed atoms (in red and green, à la git diff). I could implement a diffing algorithm returning the list of added and removed atoms per relation; however I think it'd be better to pass valuations rather than strings as parameters (I just need to know what Java type has been defined for valuations in Alloy?).

That would be great, but would require changing the code a bit. Currently the text/table views don't really store any information about the instance, they are just passed a string to be displayed.
