### ISSUE TITLE
Publish releases in Maven Central

### ISSUE THREAD

**Issue by serras** [AlloyTools/org.alloytools.alloy#196]
Right now snapshots are published in the corresponding repository, but the actual releases aren't. It would be great if those were available in [Maven Central](https://search.maven.org/), so a project can depend on those.

**Comment by serras** [comment]
We currently [depend on `SNAPSHOT`](https://github.com/47degrees/karat/blob/main/gradle/libs.versions.toml#L8) in one of our projects which uses Alloy as a library.

**Comment by pkriens** [comment]
Duplicate of #126
