### ISSUE TITLE
Remove `disjoint` keyword

### ISSUE THREAD

**Issue by grayswandyr** [AlloyTools/org.alloytools.alloy#205]
I just discovered this [keyword](https://github.com/AlloyTools/org.alloytools.alloy/blob/67d86b89f227e46aed42bce70be2edb6fc6403b2/org.alloytools.alloy.core/parser/Alloy.lex#L184), a synonym for `disj`. @dnjackson do you agree to the removal?

**Comment by dnjackson** [comment]
I didn't even know it existed, and I think it's good to remove it.

**Comment by nmacedo** [comment]
Removed for 6.2.
