### ISSUE TITLE
Warn the user about in-line implicit conjunctions

### ISSUE THREAD

**Issue by nmacedo** [AlloyTools/org.alloytools.alloy#212]
In-line implicit conjunctions are a source of confusion and give rise to tricky specification errors. We've discussed the possibility to either throw an error or give a warning to the user when they are used. Both are doable, which should we implement?

**Comment by grayswandyr** [comment]
Issue a warning. Show how it's parsed.

**Comment by nmacedo** [comment]
Would this work?
<img width="1055" alt="Screenshot 2023-04-15 at 14 55 11" src="https://user-images.githubusercontent.com/3604584/232228667-d74f70bb-035f-49ba-bf61-95d6edec0dec.png">

**Comment by grayswandyr** [comment]
Perfect!
