### ISSUE TITLE
Selected text is not highlighted in the Evaluator

### ISSUE THREAD

**Issue by grayswandyr** [AlloyTools/org.alloytools.alloy#221]
When selecting text of previous commands in the Evaluator (using double-click), the selection isn't highlighted (but does work as you can, e.g. copy paste the said text with `ctrl+C/ctrl+V`).

**Comment by pkriens** [comment]
A4 or CLI evaluator? If it is the CLI, that would depend on your shell?

**Comment by grayswandyr** [comment]
Evaluator.

**Comment by grayswandyr** [comment]
Sorry, too fast copy-paste. Evaluator in A4. I suggest we call the CLI one "Alloy Shell" to avoid ambiguities.

**Comment by nmacedo** [comment]
Is this what you mean? Seems to work on my machine (mac).

<img width="399" alt="Screenshot 2024-03-28 at 15 14 35" src="https://github.com/AlloyTools/org.alloytools.alloy/assets/3604584/1e36ff16-bbc8-4f76-92c0-bbd28d1f5ef9">

**Comment by grayswandyr** [comment]
Yes. This must be yet another UI issue with the GNU/Linux version then. Let's close this then, thanks for considering the issue.
