### ISSUE TITLE
Missing extended visualizer?

### ISSUE THREAD

**Issue by zmitchell** [AlloyTools/org.alloytools.alloy#223]
I downloaded the latest official JAR and ran `java -jar <path/to/jar>` executed a simple model, and the visualizer doesn't have the buttons for "New Init", "New Fork", etc as seen in the screenshots in this post: https://alloytools.org/alloy6.html

All I have for exploring is the "New" button. Is there a setting somewhere that I'm missing?

System info:
- macOS 13.4, M1 Max
- Alloy 6.1.0 built 2021-11-03T15:25:43.736Z

**Comment by alcinocunha** [comment]
Are all your sigs and fields static (not declared with `var`)? If so, then you will see only one "New" button. The other "News" only appear when you have something mutable.

**Comment by zmitchell** [comment]
Ah, you’re exactly right, I’ve only been playing around with static stuff so far. Thanks, I thought I was losing my mind!
