### ISSUE TITLE
Use a different color for every sig from scratch when opening Viz (a.k.a poor man's magic layout)

### ISSUE THREAD

**Issue by grayswandyr** [AlloyTools/org.alloytools.alloy#229]
When opening the Visualizer, every sig has the same shape and color by default. It would be more readable if every sig was assigned a distinct color from scratch. Doing this only would make diagrams much more readable while not changing their layout (contrary to changing shapes or even Magic Layout, which could remain up to the user). An option could exist to keep the old full-yellow behavior if people think it's necessary.

**Comment by grayswandyr** [comment]
Private communication: @dnjackson suggests to make this an option of Magic Layout. He fears cases where one would want to undo the theming, in which case it would be a real pain.

**Comment by nmacedo** [comment]
The way things work for edges is that there is a color named "magic" that assigns different colors to edges sequentially. I can also add that "magic" color to nodes. If you go to sig "univ" and set its color to "magic", all other sigs will have different colors (since they will inherit "magic" by default).

**Comment by nmacedo** [comment]
It would be something like this, if you select "magic" at the top:
<img width="978" alt="Screenshot 2024-03-26 at 17 57 29" src="https://github.com/AlloyTools/org.alloytools.alloy/assets/3604584/b9356778-2d58-4b34-bf0a-42e5897fcc51">

But then you can still customize individual sigs:
<img width="978" alt="Screenshot 2024-03-26 at 17 59 28" src="https://github.com/AlloyTools/org.alloytools.alloy/assets/3604584/886b5094-be31-45c7-a3d6-b93278fb2c90">

And if you get tired of "magic", you can just change the default back to other color:
<img width="978" alt="Screenshot 2024-03-26 at 18 00 13" src="https://github.com/AlloyTools/org.alloytools.alloy/assets/3604584/b8502380-6f0e-4b14-bd11-c7b03e52a587">

This is exactly how edge color already works.

**Comment by grayswandyr** [comment]
That's great! Following up on @dnjackson's comment, please just ensure that the default color remains yellow. And as for relations, the color should remain the same from state to state.
