### ISSUE TITLE
Add colorblind-friendly palette

### ISSUE THREAD

**Issue by grayswandyr** [AlloyTools/org.alloytools.alloy#234]
A standard reference is https://personal.sron.nl/~pault/#sec:qualitative
I suggest in particular extracts of the palette called "Bright" by Paul Tol, i.e:
blue '#4477AA' 
green '#228833', 
yellow '#CCBB44', 
red '#66CCEE',
grey '#BBBBBB'.

**Comment by nmacedo** [comment]
Done! Quick question: for "red" you suggested the color "cyan" from the Bright palette, is that right?

**Comment by grayswandyr** [comment]
My bad: red is '#EE6677'. The rest is OK.
