### ISSUE TITLE
Evaluator not recognizing variable name. Error: The name cannot contain the '$' symbol.

### ISSUE THREAD

**Issue by luomein** [AlloyTools/org.alloytools.alloy#235]
Alloy 6.1.0, Mac OS 13.6.3

In the Evaluator, sometimes the variable name will raise error, The name cannot contain the '$' symbol.

{Node$0} ---> work fine
{Node$1} ---> work fine
{Node$0} + {Node$1} ---> work fine
{Node$0, Node$1} ---> error1
{(Node$0), (Node$1)} ---> error2
{List$0->Node$0, List$0->Node$1} ---> error2

error1: 
The name cannot contain the '$' symbol.

error2:
Syntax error at line 1 column 10:
There are 38 possible tokens that can appear here:
! # ( * @ Int NAME NUMBER STRING String ^ after all always before disj eventually fun historically iden int let lone no none once one pred seq set some steps sum this univ { } ~

<img width="1029" alt="image" src="https://github.com/AlloyTools/org.alloytools.alloy/assets/2898897/badd3c9e-d125-4fe7-8f3e-dae195634ef1">

**Comment by pkriens** [comment]
The '{' is not valid Alloy syntax. Message could be better but the curly braces are the problem. This works:
```alloy
(Node$0+Node$1) & Node$1
```
For convenience, you can also use the `Foo¹` that you can copy from the output.
