### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by pkriens** [AlloyTools/org.alloytools.alloy#25]

**Comment by pkriens** [comment]
![image](https://user-images.githubusercontent.com/200494/36424445-96496464-1643-11e8-9c06-e6b5ef8f06cf.png)
![image](https://user-images.githubusercontent.com/200494/36424507-ca1fd124-1643-11e8-89fe-a806e2cf8281.png)
![image](https://user-images.githubusercontent.com/200494/36426933-fd0082c0-164b-11e8-8075-3848e0be37ea.png)
![image](https://user-images.githubusercontent.com/200494/36427315-2c4ce9aa-164d-11e8-9062-86d2c30c39f0.png)
![image](https://user-images.githubusercontent.com/200494/36427349-4a737e4e-164d-11e8-875e-0cf1da4f742e.png)

**Comment by aleksandarmilicevic** [comment]
What's the issue here?

**Comment by pkriens** [comment]
Sorry, no issue. Just a place holder for images
