### ISSUE TITLE
Include derived functions from imported modules

### ISSUE THREAD

**Issue by nmacedo** [AlloyTools/org.alloytools.alloy#250]
Functions without parameters defined in the main module show up in the visualizer. However, functions without parameters from imported modules are never included in the visualization (think of the `next` relation from `util/ordering`). This doesn't seem consistent since sigs/fields from imported modules appear in the visualization, and imported derived functions are still available in the evaluator.

**Comment by grayswandyr** [comment]
Very important indeed! I'll add this to the 6.1 milestone for this reason. Feel free to remove the milestone if that is too much work.

PS: IIRC, macros aren't imported either.

**Comment by nmacedo** [comment]
Here's how it would look for `util/ordering`. I left the names qualified to avoid confusion. Of course, these elements can be hidden/customized in the theme like any others.
 
<img width="1074" alt="Screenshot 2024-05-15 at 12 23 41" src="https://github.com/AlloyTools/org.alloytools.alloy/assets/3604584/e2dcb47a-fe3d-458e-a15c-73c42f74b43f">
