### ISSUE TITLE
Editor pane goes crazy after hitting Ctrl+Shift+O 

### ISSUE THREAD

**Issue by grayswandyr** [AlloyTools/org.alloytools.alloy#257]
This issue is present in (at least) A6 and A6.1-alpha, at least on Linux. 
Take the following edition:
![image](https://github.com/AlloyTools/org.alloytools.alloy/assets/8328276/ed66ed4b-2ab8-422a-a4b5-0be47e821440)

After hitting Ctrl+Shift+O, the edition frame goes blank (and Ctrl+Z doesn't seem to bring it back). Behind the scene, it seems characters are taken into account since the line and column counters change if some text is input.
![image](https://github.com/AlloyTools/org.alloytools.alloy/assets/8328276/ce702ef5-86bc-4842-9c97-e8f3475ef935)

Users might lose a model because of a bad keystroke.

**Comment by nmacedo** [comment]
I can't find that shortcut on the source code (nor on the macos GUI), what was it supposed to do?

**Comment by grayswandyr** [comment]
Nothing that I know :-) 
I typed it mistakenly and it blew my model away. And Undo doesn't fix this.

**Comment by nmacedo** [comment]
Ok, after some digging it seems like that is a shortcut from swing's JTextPane that toggles the orientation of the component. Why it is causing that weird behaviour in the Analyzer is beyond my expertise, what I can do is just disable that shortcut :)

**Comment by grayswandyr** [comment]
Looks safer!
