### ISSUE TITLE
Model not processed with dash header

### ISSUE THREAD

**Issue by nmacedo** [AlloyTools/org.alloytools.alloy#259]
`.als` models starting with a long `---` are not processed and interpreted as empty. I think this has to do with markdown models (I though these needed an `.md` extension?), but there is no visual indication in the editor.

<img width="466" alt="Screenshot 2024-04-11 at 15 33 12" src="https://github.com/AlloyTools/org.alloytools.alloy/assets/3604584/2ee4788d-b540-4919-abb4-df26febcde62">

In fact, even with exactly `---` the syntax highlighting seems to be buggy.

<img width="431" alt="Screenshot 2024-04-11 at 15 36 35" src="https://github.com/AlloyTools/org.alloytools.alloy/assets/3604584/09e8c640-4d0d-447f-aab4-111afa3ac068">

**Comment by awwaiid** [comment]
Even a single `-` or `--` should be a syntax error too, right? When not in markdown-mode, that is.

**Comment by awwaiid** [comment]
As you suspected, a file stating with `---` is switched into markdown mode here, https://github.com/AlloyTools/org.alloytools.alloy/blob/master/org.alloytools.alloy.core/parser/Alloy.cup#L300

Would you like me to remove that so that it strictly goes off of the file extension?

**Comment by awwaiid** [comment]
Well over in org.alloytools.alloy.core/src/main/java/edu/mit/csail/sdg/alloy4/OurSyntaxDocument.java it also assumes this behavior. I opened up https://github.com/AlloyTools/org.alloytools.alloy/pull/265 as what I think is a correct compromise -- strictly allowing `---\n` (with a newline) to indicate that it is a markdown file.

**Comment by pkriens** [comment]
this should be fixed nu #265
