### ISSUE TITLE
Remove deprecated "show evaluator" menu option

### ISSUE THREAD

**Issue by nmacedo** [AlloyTools/org.alloytools.alloy#260]
There's a "Show Evaluator" option under menu "Execute" that just prints 

> Note: the evaluator is now in the visualizer. Just click the "Evaluator" toolbar button when an instance is shown in the visualizer.

That has been the case at least since Alloy 4 in 2009, so I suggest to remove it.

**Comment by awwaiid** [comment]
:heavy_check_mark:

**Comment by grayswandyr** [comment]
:+1:

**Comment by pkriens** [comment]
fixed
