### ISSUE TITLE
CLI no longer outputs to STDOUT by default (dev version)

### ISSUE THREAD

**Issue by awwaiid** [AlloyTools/org.alloytools.alloy#264]
Instead you have to pass `-o --` explicitly to get it to send to STDOUT. I think the default should go back to STDOUT, but if we want the behavior that you have to explicitly pass this in then the documentation should be updated.

**Comment by pkriens** [comment]
The -o option now specifies a directory for the output files. When not specified, it defaults to the name of the source file minus the extension. To output to console, use '-'.

Help adjusted.
