### ISSUE TITLE
Add warning/message to recall that some bounds should be exact

### ISSUE THREAD

**Issue by grayswandyr** [AlloyTools/org.alloytools.alloy#29]
Some modules impose their formal parameter to be exact. E.g. `util/ordering` starts with:
```
module util/ordering[exactly elem]  
```
IMO when executing a command, the user should be warned if the corresponding signature(s) have not been explicitly specified as exact in the command. The rationale is to avoid situations where the user does not realize she has forgotten this exactness.
So, provided `S` is ordered, this should yield a warning:
```
run cmd1 for 5
```
and this should not:
```
run cmd1 for 5 but exactly 5 S
```

**Comment by pkriens** [comment]
I think Alloy is forcing any ordered sig to be exactly the scope? Otherwise none of the examples in the book with Time would work?

**Comment by grayswandyr** [comment]
Yes, Alloy does this, not only for `util/ordering` but for any module beginning by something like:
```
module mymodule[exactly X]
```
I think that, from a software engineering point of view, in particular for beginners, it is good practice to write explicitly `exactly` in commands for the concerned sigs, all the same. This way the user confirms (s)he knows that the sig is exact; otherwise (s)he may have missed this information.

**Comment by grayswandyr** [comment]
After discussion: better to show in the output frame the actual command that is run, with its computed scopes (that may even grow, sometimes).

**Comment by nmacedo** [comment]
Would something like this work? It's with verbosity set to low.
<img width="1147" alt="Screenshot 2023-04-15 at 14 20 26" src="https://user-images.githubusercontent.com/3604584/232226510-3106621c-6571-463b-8457-33022d4f1765.png">

**Comment by grayswandyr** [comment]
Change the syntax on the Scopes line to mimic the syntax of actual commands, but with all bounds.
