### ISSUE TITLE
Which JVM to use?

### ISSUE THREAD

**Issue by sfre-coop** [AlloyTools/org.alloytools.alloy#298]
The README says "requires 1.8 (and NOT 1.9, gradle does not run on 1.9)". Is this still true?

**Comment by sfre-coop** [comment]
David Chermouil says on Discourse that it should be Java 21.

**Comment by pkriens** [comment]
Minimum VM is 17 for the current build.

**Comment by sfre-coop** [comment]
That's good to know. The README still says 1.8.

**Comment by pkriens** [comment]
We're in the release process. Just made a PR with some changes.

**Comment by sfre-coop** [comment]
Thanks.
