### ISSUE TITLE
Alloy (4.2 or 5.0 beta 4) does not work with Java 9 on macOS High Sierra

### ISSUE THREAD

**Issue by danielleberre** [AlloyTools/org.alloytools.alloy#32]
I tried to run Alloy 4.2 and Alloy 5.0beta 4 on my Mac with High Sierra and Java 9.

I get the following exception:

`Exception: class java.lang.NoSuchMethodError
Message: java.lang.NoSuchMethodError: com.apple.eawt.Application.addPreferencesMenuItem()V
Stacktrace:
class java.lang.NoSuchMethodError: com.apple.eawt.Application.addPreferencesMenuItem()V
edu.mit.csail.sdg.alloy4whole.SimpleGUI.<init>(SimpleGUI.java:1546)
edu.mit.csail.sdg.alloy4whole.SimpleGUI.<init>(SimpleGUI.java:179)
edu.mit.csail.sdg.alloy4whole.SimpleGUI$7.run(SimpleGUI.java:1519)
java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
java.base/java.security.AccessController.doPrivileged(Native Method)
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

I have been using Alloy 4.2 on that Mac for 4 years without problem with previous versions of the OS and Java JVM.

**Comment by pkriens** [comment]
4.2 does not work anymore on the  Mac due to MacOS changes ... Basically Java is no longer supported and Alloy 4.2 does not run on Java 9.

The 5.0 beta installs its own VM. Did you get that stack trace from Alloy 5 Beta???

Could you try installing https://github.com/AlloyTools/org.alloytools.alloy/releases/tag/v5.0.0-markdown ?

**Comment by specifcampusdev** [comment]
Ok, I used to download only the jar file. This is what I did for that release too. Let me install the pkg.

**Comment by danielleberre** [comment]
Ok, I used to download only the jar file. This is what I did for that release too. Let me install the pkg.

**Comment by danielleberre** [comment]
Using the pkg Alloy 5 works like a charm, thanks. Closing the issue.

May I suggest that you emphasize that the jar file should not be used for macOS High Sierra?

**Comment by pkriens** [comment]
> May I suggest that you emphasize that the jar file should not be used for macOS High Sierra?
Could you post a PR for this?

**Comment by danielleberre** [comment]
I do not think it is possible to create a PR for a release description, right?
