### ISSUE TITLE
Couldn't open modules which is an alloy module file as markdown style

### ISSUE THREAD

**Issue by cutsea110** [AlloyTools/org.alloytools.alloy#55]
I installed Alloy-5.0.0.1 on windows 10 system.
And I try the new feature - [markdown syntax](https://github.com/AlloyTools/org.alloytools.alloy/wiki/5.0.0-Change-List#markdown-syntax).

My tring code are:

<pre>
---
title: Foo
layout: default
---

```alloy
sig Foo{
}
```
</pre>

and

<pre>
---
title: Bar
layout: default
---

```alloy
open Foo
```
</pre>

I succeed to execute Foo.md on my alloy analyzer.
But I got error at executing Bar.md and alloy analyzer highlighted my code 'open Foo' line.

<pre>

Starting the solver...

A syntax error has occured:
This module cannot be found.
It is not a built-in library module, and it cannot be found
at
"C:\Users\cut-sea\project\alloy\study-for-curriculum-by-alloy\Foo.als".
</pre>

Could i import my Foo.md as markdown style ?

**Comment by pkriens** [comment]
Did you call it C:\Users\cut-sea\project\alloy\study-for-curriculum-by-alloy\Foo.als

**Comment by cutsea110** [comment]
No, My project files are Foo.md and Bar.md.

**Comment by pkriens** [comment]
Alloy is looking for Foo.als ... 

I guess for Alloy this is ok since Alloy does not care what the extension is when it edits a file. I.e. the markdown is supported also when it is called .als. However, this won't work on Github ...

I guess we could also look for an '.md' file but that will require an ok from the others on the team. @aleksandarmilicevic  @eskang ?

**Comment by cutsea110** [comment]
I’m developping models,preds and asserts on alloy analyser now.
I’d like to make my alloy codes a specification like as [Dining Philosophers](https://github.com/pkriens/pkriens.github.io/blob/master/philosophers.md), and to share it with my team members.

Do you have any good ideas?

**Comment by pkriens** [comment]
I've committed a branch that also checks for '.md' files when it cannot find a '.als' file.

This needs to be approved by one of the other committers. Once that is done, it will be available from https://oss.sonatype.org/content/repositories/snapshots/org/alloytools/org.alloytools.alloy.dist/5.0.0-SNAPSHOT/ (pick the latest date then.) We probably do another release in the next few weeks. If you're really stressed, send me a mail and I send you a jar file.

**Comment by cutsea110** [comment]
Thank you!
I'll try SNAPSHOT and wait the release.

**Comment by pkriens** [comment]
It is currently in the snapshot repository.

**Comment by cutsea110** [comment]
HI, pkriens.

I've tried [SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/alloytools/org.alloytools.alloy.dist/5.0.0-SNAPSHOT/org.alloytools.alloy.dist-5.0.0-20180605.065919-25.jar).
But I got the same error.

Please reconfirm [this patch](https://github.com/AlloyTools/org.alloytools.alloy/commit/94f89b853d78f41e254da45e16b406dc108b2d1d).
I guess the path "Util.jarPrefix() + "models/" is wrong, isn't it?
I'd like to execute .md on my project directory.
