### ISSUE TITLE
AGAIN: Couldn't open modules which is an alloy module file as markdown style

### ISSUE THREAD

**Issue by cutsea110** [AlloyTools/org.alloytools.alloy#57]
About [Couldn't open modules which is an alloy module file as markdown style](https://github.com/AlloyTools/org.alloytools.alloy/issues/55), the issue has been closed.

I've tried [SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/alloytools/org.alloytools.alloy.dist/5.0.0-SNAPSHOT/org.alloytools.alloy.dist-5.0.0-20180605.065919-25.jar).
But I got the same error.

Please reconfirm [this patch](https://github.com/AlloyTools/org.alloytools.alloy/commit/94f89b853d78f41e254da45e16b406dc108b2d1d).
I guess the path "Util.jarPrefix() + "models/" is wrong, isn't it?
I'd like to execute .md under my project directory.

**Comment by pkriens** [comment]
Give it another try ... now I actually tested it. :-(

**Comment by cutsea110** [comment]
I checked new [SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/alloytools/org.alloytools.alloy.dist/5.0.0-SNAPSHOT/org.alloytools.alloy.dist-5.0.0-20180618.090528-26.jar)  just now and confirmed that it works well. :-)

Thanks!

**Comment by pkriens** [comment]
thanks for confirming!
