### ISSUE TITLE
Editor too slow

### ISSUE THREAD

**Issue by roehst** [AlloyTools/org.alloytools.alloy#60]
Hi, the Alloy GUI gets *really* slow on my computer.

How can I help solve it? I have little knowledge of debugging/profiling Java UI code.

I run ubuntu 16 with the gnome desktop manager.

**Comment by sorawee** [comment]
Do you happen to open the visualizer (the dialog that shows an instance)? This might be related to #40. Try closing the visualizer and see if the performance improves.

**Comment by roehst** [comment]
yes, with the visualizer open. i will close this in favor of #40.
