### ISSUE TITLE
Alloy crashes when pressed any key on a Mac

### ISSUE THREAD

**Issue by nguyenthanhvuh** [AlloyTools/org.alloytools.alloy#64]
I just downloaded Alloy.  After installing the legacy JDK as required when run on High Sierra, I can open the tool, but then any key press will produce a window saying "Sorry, a fatal internal error has occurred".  I have sent the bug report, but thought that I would post the issue here too, just in case others search for it.

**Comment by nguyenthanhvuh** [comment]
Actually, I just realize that clicking the "Send the Bug Report" also crashes.  It says "Sorry, an error has occurred in posting the bug report).  Attached is an image. 
![alloycrash](https://user-images.githubusercontent.com/20884260/42972772-44071b58-8b76-11e8-90cc-3f402c02f0c0.png)

**Comment by aedile** [comment]
+1 this is happening for me with Alloy 4.2

**Comment by LMolte** [comment]
Had the same problem. I downloaded version 5.0.0.1 beta .pkg from this page and had no issues, legacy JDK is not even required.
https://github.com/AlloyTools/org.alloytools.alloy/releases

**Comment by LorenzoFernando** [comment]
I created a workaround to this issue since the _Software Abstractions_ book relies on Alloy 4 and I was having issues using Alloy 5 with the published code. My solution is linked below, let me know if there are any capabilities that should be added.

https://github.com/LorenzoFernando/alloy4mac

**Comment by LorenzoFernando** [comment]
That was my deduction from [1] the book clearly saying it's written for Alloy 4, and [2] the book's code examples, copied from the website, failing to run in Alloy 5. I couldn't seem to find documentation that detailed the differences between v4 and v5 so I whipped together this solution so that I could get to learning. 

I'm a complete novice here, so if the code from the book SHOULD work with Alloy 5, please let me know. Thanks.

**Comment by ldavis-sd** [comment]
Also, this issue indicates that there ARE differences between the two: https://github.com/AlloyTools/org.alloytools.alloy/issues/75

**Comment by pkriens** [comment]
I am not aware of any example in Daniel's book that would not work. If so, then we should fix it since 4.2 really is a goner and not maintained anymore.

**Comment by aleksandarmilicevic** [comment]
Closing, since .pkg release for Mac addresses this issue.
