### ISSUE TITLE
Command class nameExpr member

### ISSUE THREAD

**Issue by s-arash** [AlloyTools/org.alloytools.alloy#68]
Can someone clarify the role of the field `nameExpr` of class `Command`?
For this command
```alloy
check TT{ some foo : Foo | some foo.next }
```
the `nameExpr` field is an ExprUnary with this `.toString()`: `"(some foo | some foo.next)"` and an `ExprBadJoin` subexpression. 

I'm asking because this causes `visitExpressions()` on the containing module to fail, which causes hover and doNav operations in `OurSyntaxWidget` to fail.

**Comment by pkriens** [comment]
Still a problem?

**Comment by s-arash** [comment]
I must have fixed it in my branch.
