### ISSUE TITLE
Copy text from Alloy tool and paste into Powerpoint, retaining color-coding

### ISSUE THREAD

**Issue by RogerCostello** [AlloyTools/org.alloytools.alloy#70]
The Alloy tool nicely color-codes reserved words. When I copy text from the Alloy tool and paste the text into Powerpoint, the color-coding is lost. Please provide a way to copy the text such that it can be pasted into Powerpoint (or Word) without losing the color-coding (formatting).

**Comment by graymalkin** [comment]
I've been using VSCode with [https://marketplace.visualstudio.com/items?itemName=DongyuZhao.alloy-vscode]() and [https://marketplace.visualstudio.com/items?itemName=ArashSahebolamri.alloy]().

The first extension on it's own should mean you can copy bits of alloy code with the VSCode syntax highlighting into Powerpoint (etc). The 2nd means you might not need to have two editors for a project.

**Comment by pkriens** [comment]
I think in the long run we should move to vscode completely. Closing it since this is unlikely to be picked up.
