### ISSUE TITLE
Feature Request: Line Numbers

### ISSUE THREAD

**Issue by hwayne** [AlloyTools/org.alloytools.alloy#79]
The current Alloy IDE doesn't have line numbers. I think this would help a lot!

**Comment by BElluu** [comment]
Hello. Can I take care of this task?

**Comment by pkriens** [comment]
Of course, make a PR!

If you do, you might want to think of the Markdown mode. In that case the line numbers should only be active in the Alloy sections to match warnings.

**Comment by nigelkerr** [comment]
Hello Alloy Friends,

I think to pick this line-numbers in Alloy up.  My thought is that it is a boolean Editor preference, propagating down to each instance of OurSyntaxWidget.  I base that on how font-family and font-size are set and propagated already.  I see at least one strategy that will straight-forwardly apply. 

@pkriens suggests in a previous comment that the line number behavior might want to be different in the Markdown mode, and I'd like to understand the suggestion better.  I observe that if I load an alloy-bearing .md file, and introduce a syntax error, Alloy reports the error on the line in the whole file, not just relative to the alloy markup sections.  Please advise.

**Comment by pkriens** [comment]
It is true that when I wrote the translate function to turn the markdown to Alloy, I inserted empty lines for each non-alloy line. So line numbers should match up. Not need to do anything special. Sorry for the confusion.

**Comment by nigelkerr** [comment]
Thank you @pkriens for clarification, I didn't want to miss something important.

**Comment by pkriens** [comment]
Is implemented
