### ISSUE TITLE
"An error has occurred!"

### ISSUE THREAD

**Issue by dtornow** [AlloyTools/org.alloytools.alloy#86]
Hello.

I downloaded and installed Alloy 5.0.0.201804081720 but every time I execute a model e.g.

```
sig Foo {}
```

I get the error message

```
An error has occurred!
```
without additional details.

Any ideas of how to fix or where to look for more details?

Thank you

**Comment by pkriens** [comment]
Please provide platform details (os, version, java vm version, etc.) and how you start it up

**Comment by dtornow** [comment]
I'm running the Alloy Analyzer on macOS Mojave 10.14.5, Java Version 1.7.0. I start the application by double clicking the application icon.

Thanks for your help

**Comment by aleksandarmilicevic** [comment]
Probably something about Mojave.  I just tried it on 10.13.6 and it works fine.  I'm using Java 9 though:
```
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```
Can you try updating your Java?

**Comment by dtornow** [comment]
Updating Java did the trick! Many thanks
