### ISSUE TITLE
Files no longer ignored after code refactoring

### ISSUE THREAD

**Issue by AbderrahmanL** [AlloyTools/org.alloytools.alloy#91]
Hello,
These files (Under **org.alloytools.alloy.core/src/main/java/edu/mit/csail/sdg/parser**):
- CompLexer.java
- CompParser.java
- CompSym.java

Are generated upon build by some scripts in the same directory (as the scripts) and are supposed to be ignored, but the .gitignore(In the root of the repo) is still referencing the old path for the 3 files **(org.alloytools.alloy.application/src/main/java/edu/mit/csail/sdg/alloy4compiler/parser)**.

_It is a minor but annoying matter as whenever you build the generation date in the 3 files are changed._

Regards.

**Comment by pkriens** [comment]
This was changed in 6.0
