### ISSUE TITLE
Doesn't work on Mac OS

### ISSUE THREAD

**Issue by stereobooster** [AlloyTools/org.alloytools.alloy#95]
Mac OS version: 10.14.5 (18F132)
Alloy version: alloy4.2_2015-02-22.jar

I can't copy text from the box, because it fails with other error

<img width="456" alt="Screenshot 2019-10-04 at 11 35 11" src="https://user-images.githubusercontent.com/179534/66197658-2bc28b00-e69b-11e9-923a-c2a29e7679d0.png">

Steps to reproduce: start jar file, focus text box.

Happy to provide more details. It may happen I'm doing something wrong, but not sure what.

**Comment by pkriens** [comment]
You're running a very old Alloy. Please download the latest from https://github.com/AlloyTools/org.alloytools.alloy/releases

**Comment by stereobooster** [comment]
I searched the internet, I got to the official website and downloaded it there. I found this repo after I got the error.

I will try latest version from releases
