### ISSUE TITLE
font size error

### ISSUE THREAD

**Issue by mommy742** [AlloyTools/org.alloytools.alloy#97]
the font/text size for the evaluator window cannot be changed and is currently way to small, none of the font size options changed the text in the evaluator menu. this bug was on the 4.2 edition and is on the 5.0.0.1 version, using windows 10.
![Capture27](https://user-images.githubusercontent.com/16270026/66672098-84f66580-ec2b-11e9-8bef-61a8ca75361e.PNG)

**Comment by pkriens** [comment]
Related to #119, closing as duplicate
